### ISSUE TITLE
Flash modified firmware on M1S Gen1 CN

### ISSUE THREAD

**Issue by vit5041** [niceboygithub/AqaraM1SM2fw#103]
Hi! I am thinking to flash M1S Gen1 CN with modified firmware to integrate to HA.. Want to ask, what should I expect to happen with linked devices in Mi Home? 

upd: ..and If I use gw_global_tool for the same purpose -- should I be able to open telnet and reset password, right? What will happen to the linked devices in Mi Home?

**Comment by niceboygithub** [comment]
What do you mean that linked device in Mi Home?

**Comment by vit5041** [comment]
I mean already paired sensors in Mi Home, Zigbee child devices.
Some of them are not easily accessible, so I'd like to assess the risk of re-pairing all.

**Comment by vit5041** [comment]
So finally I went through it. There is a good chance to keep all paired devices but I did not manage. I had reset GW after making magic clicks for numerous of times to try to open telnet. 
If I would flash modified firmware from the beginning, I would have better chances to keep all linked devices.
