### ISSUE TITLE
Dose anyone know where are the Rx and Tx of my M1S?

### ISSUE THREAD

**Issue by mcmichaelchan** [niceboygithub/AqaraM1SM2fw#104]
![IMG_6761](https://github.com/niceboygithub/AqaraM1SM2fw/assets/15685780/80bbb1af-ff2a-4363-9813-f5c6031f32bb)

**Comment by ChaconC** [comment]
I have this same model, was hoping to find any info over here

Aqara M1S (CN)
Model: lumi.gateway.acn004
Hardware version: Linux
Firmware version: 4.1.0_0003.0022

**Comment by niceboygithub** [comment]
![image](https://github.com/niceboygithub/AqaraM1SM2fw/assets/74046071/6e821ff2-a621-4b65-94ad-723e64cd1820)

these pins are gnd, tx, rx.
Find the gnd pin first (use multimeter to find)

**Comment by dragouf** [comment]
Anyone can explain what is the correct procedure ? where to plug 3v and gnd with this version ?
