### ISSUE TITLE
M1S

### ISSUE THREAD

**Issue by syxuxiaoliang** [niceboygithub/AqaraM1SM2fw#115]
May I ask when the new firmware for M1S will be updated? I think the updated version is M1S2022

**Comment by niceboygithub** [comment]
What do you mean?

**Comment by syxuxiaoliang** [comment]
M1S (ZHWG15LM)   When can version 4.1.8 be released?

**Comment by niceboygithub** [comment]
I donot M1S in Aqara mode

**Comment by niceboygithub** [comment]
What do you mean?

**Comment by syxuxiaoliang** [comment]
想请问一下，m1s的4.1.8版的固件什么时候能发布
