### ISSUE TITLE
M1S-M2 power supply when flashing

### ISSUE THREAD

**Issue by eryxator** [niceboygithub/AqaraM1SM2fw#118]
It is safe to use M1S M2 power board with 220v when flashing over UART-usb board or a controller board must be powered from another source? If 220v can't be used, how to powerup the board in right way?

**Comment by niceboygithub** [comment]
M2 can use USB(5V)
M1S need use power supply board.
Suggest use fixture or soldering out.

**Comment by syxuxiaoliang** [comment]
M1S (ZHWG15LM) When can version 4.1.8 be released?
