### ISSUE TITLE
m2 eu

### ISSUE THREAD

**Issue by YanchikAmb** [niceboygithub/AqaraM1SM2fw#18]
Hi! Can I flash custom firmware to eu version hub m2? 
Do you know how enable telnet on hub m2 eu version?
How I can use Aqara Gateway integration via hub m2 eu version? 
Thanks.

**Comment by niceboygithub** [comment]
M2 gateway EU version has signed firmware. Can not flash modified fw.

To enable telnet, there is a way with high risk. Not recommend that normal users to use it.
A simple solution is to buy CN version.

**Comment by YanchikAmb** [comment]
oh I see, but in my country I can't buy zn version.
Thanks.

**Comment by vladyslav-chupryn** [comment]
Hi! Could you please also upload the bootloader for the M2 EU version? I flashed my device with https://github.com/niceboygithub/AqaraM1SM2fw/blob/main/raw/bootloader_1.0.0_0001/bootload_1.0.0_0001.bin, and it stopped booting at all?

**Comment by niceboygithub** [comment]
stay tuned for M2 EU hack

**Comment by Nismonx** [comment]
Any advances on the M2 EU hack? My skills are limited but I'm more than happy to help out.

**Comment by r3knit** [comment]
@niceboygithub > To enable telnet, there is a way with high risk.

Could you please share? I have got an almost bricked M2 EU flashed by mistake with modified fw :)

**Comment by w1tw0lf** [comment]
Also keen on the modified firmware for M2 EU version.

**Comment by niceboygithub** [comment]
Is anyone still interested on enabling telnet in M2 EU which can not flash modified firmware?

**Comment by r3knit** [comment]
@niceboygithub 
> Is anyone still interested on enabling telnet in M2 EU which can not flash modified firmware?

Of course! Maybe i can find out how to use it even with its current firmware. Or mb there is a chance to flash it with something more interesting

**Comment by niceboygithub** [comment]
Do you want to connect UART of M2?

I wrote a script that can clear the password of admin in M2.

If you wired the UART of M2, you shall use the script.

**Comment by niceboygithub** [comment]
To flash firmware of M2 EU which use signed firmware, it is impossible because there is sign key to signed firmware.
