### ISSUE TITLE
For Aqara M1S 2022

### ISSUE THREAD

**Issue by qjiang888** [niceboygithub/AqaraM1SM2fw#19]
`php miio-cli.php --ip GW_IP --token GW_TOKEN --sendcmd '{"id":123,"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d root ; /bin/riu_w 101e 53 3012; telnetd"}}'`

php-miio (https://github.com/skysilver-lab/php-miio)

fw_update Can not run

**Comment by niceboygithub** [comment]
What are you saying?
