### ISSUE TITLE
Aqara hub do not load boot

### ISSUE THREAD

**Issue by aparadox1** [niceboygithub/AqaraM1SM2fw#21]
Hi. You can help me? boot_info my aqara hub M1S have big size. How can I resize boot_info
Command db 0xa0a00000 55 return next info:
[Addr] .0 .1 .2 .3 .4 .5 .6 .7 .8 .9 .A .B .C .D .E .F
A0A00000: 7C 91 00 00 96 3B 00 00 00 00 00 20 EC 04 CB 43 |....;..... ...C
A0A00010: 00 00 20 EC 04 C8 CF 00 00 9A 40 04 74 2C 00 00 .. .......@.t,..
A0A00020: 82 80 04 62 C6 00 00 00 01 31 2E 30 2E 32 2E 30 ...b.....1.0.2.0
A0A00030: 30 35 00 00 00 00 00 00 20 00 04 00 00 00 00 20 05...... ......
A0A00040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
A0A00050: 00 00 00 00 00

**Comment by niceboygithub** [comment]
I did get your point.
Why the size boot_info become big?

The size of boot_info was fixed.
