### ISSUE TITLE
H1 hub failed to start

### ISSUE THREAD

**Issue by firesunCN** [niceboygithub/AqaraM1SM2fw#26]
Hello, My device information is as follows.
H1 hub(QBCZWG11LM) (https://www.aqara.com/cn/productDetail/smart-wall-outlet-h1-hub)
Firmware Version 3.3.6_0027

I flashed this firmware(https://github.com/niceboygithub/AqaraM1SM2fw/blob/main/modified/H1/3.2.8_0007.0525/rootfs_3.2.8_0007.0525_modified.bin) with AqaraGateway (https://github.com/niceboygithub/AqaraM1SM2fw/blob/main/tools/aqaragateway.exe)

I selected this partition 'rootfs_0', the screenshot is as follows
![image](https://user-images.githubusercontent.com/13866683/153755803-fe61e3a1-b470-4089-beae-63294084963a.png)

After I restarted the power supply, the indicator light was first white, then yellow, and after a period of time, the indicator light went out, and there was no response. Long press the reset button for 10 seconds and nothing happened. Disconnected the power and re-applied, still the same.
I tried flashing back to the original firmware (https://github.com/niceboygithub/AqaraM1SM2fw/blob/main/original/H1/3.2.8_0007.0525/root_3.2.8_0007.0525.bin) to rootfs_0 partition, still the same

Can you help to see where is the problem?

**Comment by niceboygithub** [comment]
Can you have uart log while booting?
