### ISSUE TITLE
break Bootloader M2

### ISSUE THREAD

**Issue by MinhhhCuonggg** [niceboygithub/AqaraM1SM2fw#28]
I see you have full HUB m2 firmware instead of updated firmware. How can you break Bootloader, enter the command on Hub M2 EU to get the full firmware

**Comment by niceboygithub** [comment]
It was from @rezmus 
You can interrupt the bootloader by short circuit on spi flash

**Comment by niceboygithub** [comment]
short data pin of SPI NAND flash
