### ISSUE TITLE
Add lumi.gateway.aeu01 firmware. Please!

### ISSUE THREAD

**Issue by lopatin777** [niceboygithub/AqaraM1SM2fw#32]
Please help! 
Need original firmware for lumi.gateway.aeu01.

**Comment by niceboygithub** [comment]
I do no have such device on hand. It is hard to me to provide original firmware. Maybe someone else can help.

**Comment by lopatin777** [comment]
it’s very sadly.

**Comment by maikthulhu** [comment]
I have one of these that identifies as lumi.gateway.aeu01. I'm in the US but picked it up off of Amazon. I also probably have the skills necessary to crack the case and dump the firmware.

@niceboygithub Would it be helpful if I dumped it and did a PR so you can have the image?

**Comment by martyanov1990** [comment]
Hello. Has the firmware for the m1s eu not arrived?

**Comment by Otnow** [comment]
```json
"releaseDate": 1656555792000,
"part": "main",
"downloadUrl": "https://cdn.aqara.com/cdn/opencloud-product/mainland/product-firmware/prd/lumi.gateway.aeu01/20220622151632_lumi.gateway.aeu01_AIOT_V3.4.2_0016.0616_20220622_4923c0.bin",
"upgradeTakesTime": 40,
"updateLog": "1.Optimize device related functions;\n2.Fix known issues;",
"updateTime": 1656555792000,
"isNecessary": 0,
"fileSize": 13496424,
"createTime": 1656418454000,
"firmwareMD5": "aacdef9333aee3e5b496c1c3584923c0",
"state": 3,
"isForce": false,
"firmwareVersion": "3.4.2_0016.0616",
"imageType": "bin",
"firmwareCRC32": "5DCCB0E4"
```

**Comment by lopatin777** [comment]
thanks

**Comment by sorryusernameisalreadytaken** [comment]
> ```json
> "releaseDate": 1656555792000,
> "part": "main",
> "downloadUrl": "https://cdn.aqara.com/cdn/opencloud-product/mainland/product-firmware/prd/lumi.gateway.aeu01/20220622151632_lumi.gateway.aeu01_AIOT_V3.4.2_0016.0616_20220622_4923c0.bin",
> "upgradeTakesTime": 40,
> "updateLog": "1.Optimize device related functions;\n2.Fix known issues;",
> "updateTime": 1656555792000,
> "isNecessary": 0,
> "fileSize": 13496424,
> "createTime": 1656418454000,
> "firmwareMD5": "aacdef9333aee3e5b496c1c3584923c0",
> "state": 3,
> "isForce": false,
> "firmwareVersion": "3.4.2_0016.0616",
> "imageType": "bin",
> "firmwareCRC32": "5DCCB0E4"
> ```

@Otnow can you help us here getting more details about your trick to get the direct dl links?
https://github.com/Koenkk/zigbee2mqtt/discussions/13193

**Comment by Otnow** [comment]
@sorryusernameisalreadytaken, answered in discussion https://github.com/Koenkk/zigbee2mqtt/discussions/13193.
