### ISSUE TITLE
use scripts update m1s fw shows Update failed, reason: getpack failed!

### ISSUE THREAD

**Issue by casatift** [niceboygithub/AqaraM1SM2fw#34]
use scripts update m1s fw shows Update failed, reason: getpack failed!

> # chmod a+x /tmp/m1s_update.sh && /tmp/m1s_update.sh
m1s_update.sh revision: 2
type: lumi.gateway.acn01, model: AH_M1S
platform: aiot, path: /tmp, sign: 0
Unpack path : /tmp/ota_dir
Firmware path : /data/ota_dir
Available ROM size(b): 26251264
Available RAM size(b): 22396928
Get packages, please wait...
Update failed, reason: getpack failed!

**Comment by mikeinblue** [comment]
The same problem.

**Comment by wzguzi** [comment]
Same here.

**Comment by niceboygithub** [comment]
I fixed it. Please try again.

**Comment by vinter-wu** [comment]
# chmod a+x /tmp/m1s_update.sh && /tmp/m1s_update.sh
m1s_update.sh revision: 2
type: lumi.gateway.acn01, model: AH_M1S
platform: miot, path: /tmp, sign: 0
Unpack path : /tmp/ota_dir
Firmware path : /data/ota_dir
Available ROM size(b): 26394624
Available RAM size(b): 15499264
Get packages, please wait...
md5sum: can't open '/tmp/rootfs.bin': No such file or directory
Update failed, reason: getpack failed!
