### ISSUE TITLE
aqaragateway.exe no response

### ISSUE THREAD

**Issue by hongqian** [niceboygithub/AqaraM1SM2fw#35]
![image](https://user-images.githubusercontent.com/14159505/163720030-b35fccab-1f51-4ca8-b292-7cd263fbd932.png)
Flash rootfs_3.4.0_0004.0616_modified.bin stuck at this step

**Comment by hongqian** [comment]
![lADPJxf-wxswTIPNAnbNBF4_1118_630](https://user-images.githubusercontent.com/14159505/163720182-5210c7cc-aa16-4669-ad12-fcaa21458eb8.jpg)

**Comment by niceboygithub** [comment]
First, what is your M2 version? China or EU?

It did not continue to flash because it can not detect bootcode. Try to check tx/rx/gnd and complete power off before power up.
