### ISSUE TITLE
Help!Aqara M2(ZHWG17LM) flashing failed.

### ISSUE THREAD

**Issue by yuyamin** [niceboygithub/AqaraM1SM2fw#39]
I've received several M2 gateways yesterday. However, after using the Aqara_Gateway_Utils to flash the firmware, it failed. Flashing stopped at "Downloading the flasher".After the tool finished downloading the firmware, it stopped. How could i flash the firmware?Thank u
![截图20220528151107](https://user-images.githubusercontent.com/52734710/170814859-6deca6a9-52c7-43a3-b4af-5f40fcbb8042.png)
!

**Comment by niceboygithub** [comment]
remove the power cable of M2 and try again

**Comment by niceboygithub** [comment]
Sorry, I don’t have ZHWG17LM to test

**Comment by niceboygithub** [comment]
Duplicated #45
