### ISSUE TITLE
Could you provide more internal photos of the M2 or which Zigbee chipset is used?

### ISSUE THREAD

**Issue by TheDevFreak** [niceboygithub/AqaraM1SM2fw#4]
Looking to find out which Zigbee chip is used in this device, could you post the model number of it or provide more internal photos showing the chips of the M2 hub?

**Comment by niceboygithub** [comment]
NXP JN5189

**Comment by TheDevFreak** [comment]
> 
> 
> NXP JN5189

Just wondering if you have more information. Can this custom firmware be used for ZHA in home assistant?

**Comment by niceboygithub** [comment]
ZHA not support JN5189
