### ISSUE TITLE
m1s  only lights up 

### ISSUE THREAD

**Issue by douglasleft** [niceboygithub/AqaraM1SM2fw#43]
Which firmware should I choose to flash?
I have tried flash linux_3.4.2**.bin on linux_0 and linux_1  
 root_3.4.2**.bin on roottfs_0 and roottfs_1
The m1s still only lights up, first yellow, then blue
does ControlBridge.bin need to be flashed, which one to choose?

**Comment by niceboygithub** [comment]
Please flash to ControlBridge.bin to latest!

**Comment by borpsky** [comment]
how to flash ControlBridge.bin

**Comment by miniknife88** [comment]
How to flash ControlBridge.bin use tool

**Comment by niceboygithub** [comment]
copy ControlBridge.bin to M1S and use this command after telnet

```
zigbee_msnger zgb_ota ControlBridge.bin
```
