### ISSUE TITLE
Aqara P3 UART TTL and power pins

### ISSUE THREAD

**Issue by 665465** [niceboygithub/AqaraM1SM2fw#57]
I just missed flash a wrong firmware into Aqara P3. Now the device doesn't boot anymore. I opened the case but the UART pins are n't labeled. 
Could someone share the UART and power pins position ? I want to try flash firmware by xmodem into P3.
Thanks.
![image](https://user-images.githubusercontent.com/3960822/201505356-d8eb41da-b4b1-49a5-b0ed-304e89450f05.png)

**Comment by Nismonx** [comment]
I don't have one so can't help you much. Just though of mentioning if you lookup the MCU schematics and with the help of a multimeter you should be able to narrow it down. Or just wait for someone to come and help ¯\_(ツ)_/¯

**Comment by 665465** [comment]
> I don't have one so can't help you much. Just though of mentioning if you lookup the MCU schematics and with the help of a multimeter you should be able to narrow it down. Or just wait for someone to come and help ¯_(ツ)_/¯

Thanks.
I've found the GND/Power and Tx pin. Not sure about the Rx because the device stuck in boot loop and is not responding to key input.
![image](https://user-images.githubusercontent.com/3960822/203087036-5cc675d8-03ce-4ab6-92ad-77c500f8c5d8.png)

![image](https://user-images.githubusercontent.com/3960822/203085679-33079ff3-79c0-40e1-ba9b-b9d867905098.png)

And it seems there is no option in aqaragateway tool for Aqara P3 gateway. Is there any other way I can flash the FW into the gateway?
![image](https://user-images.githubusercontent.com/3960822/203087165-ba2fc85f-db42-4ed9-914b-26dde4b1b9c1.png)

**Comment by niceboygithub** [comment]
Can you provide the log that can not boot up?

**Comment by 665465** [comment]
Please see the attachment for the full log. I flashed a Xiaomi gateway 3 firmware into P3 by mistake. Seems there is even no way to get into uboot?
[full_log.txt](https://github.com/niceboygithub/AqaraM1SM2fw/files/10258443/full_log.txt)

**Comment by niceboygithub** [comment]
You can flash P3 firmware by choose M1S model.
