### ISSUE TITLE
aqaragateway.exe

### ISSUE THREAD

**Issue by xztxy** [niceboygithub/AqaraM1SM2fw#6]
aqaragateway.exe    Failed to execute script  ?

**Comment by niceboygithub** [comment]
Failed?

Do you have screenshot?

**Comment by xztxy** [comment]
![image](https://user-images.githubusercontent.com/31698398/109254931-fbe6cb00-782d-11eb-9e23-fc7041b94cca.png)

**Comment by xztxy** [comment]
> Failed?
> 
> Do you have screenshot?

![image](https://user-images.githubusercontent.com/31698398/109254961-0d2fd780-782e-11eb-8c68-1a5d8cda963f.png)

**Comment by niceboygithub** [comment]
Do you insert USB2UART?
