### ISSUE TITLE
P3 gateway modified firmware latest version

### ISSUE THREAD

**Issue by ashottonoyan** [niceboygithub/AqaraM1SM2fw#60]
Will there be a modified update to 3.4.8 for P3 or should I just use the M1S modified firmware?

**Comment by niceboygithub** [comment]
Do NOT use M1S firmware on P3!!


Please provided the latest stock P3 firmware then I can create modified one

**Comment by ashottonoyan** [comment]
How do I get the latest stock version? I have already flashed the latest modified one.

**Comment by tsunglung** [comment]
reference to [this](https://github.com/niceboygithub/AqaraM1SM2fw/issues/58#issuecomment-1357364825)

**Comment by ashottonoyan** [comment]
now 3.5.0 is out.

https://cdn.aqara.com/cdn/opencloud-product/mainland/product-firmware/prd/lumi.aircondition.acn05/20221229202616_lumi.aircondition.acn05_AIOT_V3.5.0_0015.0636_20221227_eff26a.bin

**Comment by ashottonoyan** [comment]
Thanks!
