### ISSUE TITLE
Any modified firmware for M1S 2022 CN?

### ISSUE THREAD

**Issue by ashottonoyan** [niceboygithub/AqaraM1SM2fw#61]

**Comment by SikaiGGMU** [comment]
it seems like M1S 2022 CN changed its soc, and the instruction architecture switches from mips32 to arm v7

**Comment by niceboygithub** [comment]
No plan to create modified firmware for M1S 2022 CN.
M1S 2022 CN was supported in AlexxIT's [openmiio_agent](https://github.com/AlexxIT/openmiio_agent)
The openmiio_agent can run in M1S 2022 CN.

**Comment by SikaiGGMU** [comment]
Will the uart tx rx layout of M1S2022CN be published in the near future ?

**Comment by SikaiGGMU** [comment]
I accidently erased my active rootfs block, which turned my device into a 'brick'. Probably, only uart can save my device.

**Comment by SikaiGGMU** [comment]
I accidently erased my active rootfs block, which turned my device into a 'brick'. Probably, only uart can rescue my device.

**Comment by SikaiGGMU** [comment]
Hi, will it be published?

**Comment by niceboygithub** [comment]
Publish what?

**Comment by SikaiGGMU** [comment]
uart tx rx layout of M1S2022CN
