### ISSUE TITLE
M1S rootfs_3.5.2_modified.bin Unsupported sign

### ISSUE THREAD

**Issue by SikaiGGMU** [niceboygithub/AqaraM1SM2fw#64]
It seems that Aqara add signature mechanism in its fw_update.  rootfs_3.5.2_0010.0636_modified.bin can't be flashed with fw_update

**Comment by niceboygithub** [comment]
I have no problem to update to 3.5.2

<img width="926" alt="image" src="https://user-images.githubusercontent.com/74046071/222145146-03f0f556-8f8a-4a13-88a8-c9099653ed0b.png">

Can you provide the logs?
