### ISSUE TITLE
Flashing problem

### ISSUE THREAD

**Issue by munkacsy2914** [niceboygithub/AqaraM1SM2fw#74]
Hi guys! I hav e a problem with Aqara M1S gateway flashing. It connect a CP2102 board and gw. I use RX,TX cross, GND and 3,3V from board. I running aqaragateway.exe in virtualbox Windows 10 and i try flash the new firmware. A bottom line is ending but then nothing. The buttons are blank. 
What the problem? The exmple software picture and mine difference.

**Comment by niceboygithub** [comment]
what is your screen shot?

**Comment by munkacsy2914** [comment]
Thanks your fast answer. I haven't problem. I disconnect 3.3V pin and
connect 230VAC the hub. Flash write succesfull.

niceboygithub ***@***.***> ezt írta (időpont: 2023. jún. 5.,
Hét 16:52):
