### ISSUE TITLE
P3 firmware update fail.

### ISSUE THREAD

**Issue by hawkefly** [niceboygithub/AqaraM1SM2fw#78]
I have been tried several times, the P3 will  reboot unexpectedly after    "fw_update /tmp/ota_dir/linux.bin suceess" this line .  Here's the log.

p3_update.sh revision: 2
type: lumi.aircondition.acn05, model: AC_P3
platform: aiot, path: /tmp/fw.tar.gz, sign: 0
Unpack path : /tmp/ota_dir
Firmware path : /data/ota_dir
Available ROM size(b): 20361216
Available RAM size(b): 23904256
Update to 4.0.2_0024.0644
Get packages, please wait...
Got packages done
AalUart_Open /dev/ttyS2
recv STA!
recv close ACK!
recv CRC check!
ir ota successful ir_loacl_crc = 962b, ir_msg_crc=962b
fw_update /tmp/ota_dir/linux.bin suceess
Connection closed by foreign host.

**Comment by niceboygithub** [comment]
Please try again.
