### ISSUE TITLE
aqara m2 modified firmware

### ISSUE THREAD

**Issue by will0913** [niceboygithub/AqaraM1SM2fw#79]
All mighty niceboygithub, 

I've come with my humble heart to ask for help.
I want to have my aqara m2 manage non-aqara devices, and by what I have read, I need to flash the firmware. 

I don't have any background in electronics, but I managed to open the case, bought a usb-ttl device with a ch304 chip and solder on the wires as instructed. (gnd <->gnd ; rx <-> tx ; tx <-> rx)

Next, I downloaded Aqara Gateway Util and it seems to be detecting the m2. 
` Addresses: 192.168.1.239:52752
  Weight: 0, priority: 0 
  Server: Aqara-Hub-M2-BA8C.local. 
  Properties are: 
    b'ver': b'3' 
    b'cv': b'1' 
    b'ui': b'3078793806' 
    b'pv': b'true' 
    b'id': b'lumi1.54ef4448ba8c'` 

I then downloaded the latest modified firmware file (rootfs_4.0.2_0010.0644_modified.bin) 

But when I tried to flash the file, there's an error message:
`Generating padded firmware, please wait...!
The raw firmware is invaild format.
Generate padded firmware Failed!`

I am sure I messed up somewhere.  Please help.

**Comment by niceboygithub** [comment]
How did you download the modified firmware file?
