### ISSUE TITLE
UART TTL is different in Aqara M2 2022 CN (ZHWG19LM)

### ISSUE THREAD

**Issue by michael-yangjiayu** [niceboygithub/AqaraM1SM2fw#81]
1. Where is UART for M2 2022?
2. Is modified firmwares for M2 compatible to M2 2022?

**Comment by michael-yangjiayu** [comment]
![1](https://github.com/niceboygithub/AqaraM1SM2fw/assets/43327459/f3d2e357-d509-4dc0-85cf-a7d267ca93a9)
![2](https://github.com/niceboygithub/AqaraM1SM2fw/assets/43327459/93bc5bae-2ca7-47f8-8179-35deb7838de8)

**Comment by michael-yangjiayu** [comment]
Found solution in AqaraCameraHubfw, no need to wire out.
My bad XD

**Comment by aemediatodd** [comment]
> > AqaraCameraHubfw
> 
> 怎么解决的呀，一头雾水

用u盘刷入系统[https://github.com/niceboygithub/AqaraCameraHubfw/blob/main/modified/M2PoE/telnet.md](url)

**Comment by aemediatodd** [comment]
> 在AqaraCameraHubfw中找到了解决方案，无需接线。 我的坏XD

so bro do U got that two .bin files?
