### ISSUE TITLE
New M2 Gateway Model

### ISSUE THREAD

**Issue by miniknife88** [niceboygithub/AqaraM1SM2fw#88]
Model: ZHWG19LM   Powered by POE

[https://drive.google.com/file/d/11t8XhyjXWaEVwDz6lJTvwAuc93tA6DQR/view?usp=share_link](url)

[https://drive.google.com/file/d/141obdn5baU3V3TFnJP2KqCcV0RfOMZVA/view?usp=share_link](url)

**Comment by niceboygithub** [comment]
https://github.com/niceboygithub/AqaraCameraHubfw/blob/main/modified/M2PoE/telnet.md

**Comment by miniknife88** [comment]
linux.bin and rootfs.bin  （This Link cannot be opened）

**Comment by niceboygithub** [comment]
Not released yet, maybe release after Aqara M3 is on sell

**Comment by hawkefly** [comment]
Aqara M3 is on sell now.

**Comment by niceboygithub** [comment]
> Aqara M3 is on sell now.

Will you buy one M3 to me?

**Comment by ashottonoyan** [comment]
Happy to buy. Where are you based? China, right?

**Comment by niceboygithub** [comment]
Not in China.

**Comment by miniknife88** [comment]
If possible, would be happy to provide an M3 gateway as a test

**Comment by ashottonoyan** [comment]
Ok, let me know where to ship.
