### ISSUE TITLE
Upgrading the firmware via fw_update is invalid

### ISSUE THREAD

**Issue by miniknife88** [niceboygithub/AqaraM1SM2fw#9]
M1s: 3.2.4_0014.0520
M2: 3.2.4_0010.0520

The firmware version has not changed after the upgrade is complete

**Comment by niceboygithub** [comment]
which commands you use?

**Comment by miniknife88** [comment]
Upload firmware to gateway tmp directory，use：
fw_update ./linux_3.2.7_0018_0524.bin
fw_update ./rootfs_3.2.7_0018_0524_modification.bin
reboot

Display firmware version: 3.2.7_0018.0515
![IMG_2928](https://user-images.githubusercontent.com/30946790/123263793-efe4ee80-d52b-11eb-8fcd-56bb320d0a1a.PNG)

**Comment by niceboygithub** [comment]
I update the readme for flash M2 firmware for your reference.

https://github.com/niceboygithub/AqaraGateway#flash-m2-custom-firmware-method

**Comment by miniknife88** [comment]
Follow the readme to flash the firmware, can't upgrade to 3.2.7_0018.0524
`# fw_update ./linux.bin
Info: Open ./linux.bin, size: 2233364
Info: Firmware type: Linux1
Info: data_sum: 8040
Info: Upgrade linux bank 0
Info: Write to /dev/mtdblock4, size:2233348 ...
Process: 100%
Done
Info: Verify ...
Process: 100%
Success`

`# fw_update ./rootfs.bin
Info: Open ./rootfs.bin, size: 9435156
Info: Firmware type: Root1
Info: data_sum: 0a89
Info: Upgrade rootfs bank 0
Info: Write to /dev/mtdblock5, size:9435140 ...
Process: 100%
Done
Info: Verify ...
Process: 100%
Success
`

**Comment by niceboygithub** [comment]
fw_update said the flash is success.
What is your mean that can’t upgrade?

**Comment by miniknife88** [comment]
The firmware version in aqarahome has not changed

**Comment by niceboygithub** [comment]
Did you upgrade Aqara Home to latest?
Maybe it is bug of Aqara cloud service.

**Comment by miniknife88** [comment]
aqarahome version is the latest：2.3.11

**Comment by xfzha0** [comment]
Me too.
aqara home app version: V2.3.12 
M2 firmware 3.2.8_0006.0508 to 3.2.8_0006.0526.  
fw_update said the flash is success. 
After restart ,The firmware version in aqarahome has not changed.

**Comment by niceboygithub** [comment]
You need to upgrade zigbee firmware.

update bt firmware.
```
run_ble_dfu.sh /dev/ttyS1 full.gbl 125 1
```

update zigbee firmware
```
zigbee_msnger zgb_ota ControlBridge.bin
```

**Comment by miniknife88** [comment]
update zigbee firmware error:

`zigbee ota(ver: v1.0.0) firing up, built at Mar 17 2021 10:29:17; Author: liang.                                                
wang@aqara.com
connect localhost:1883
{"cmd":"write","id":2408,"did":"lumi.0","source":"","params":[{"res_name":"8.0.2                                               
 089","value":{"file_name":"./ControlBridge.bin","version":"V3.78"}}]}

on_connect result=0
ota zigbee coordinator failed, errno =8
`

**Comment by niceboygithub** [comment]
> update zigbee firmware error:
> 
> `zigbee ota(ver: v1.0.0) firing up, built at Mar 17 2021 10:29:17; Author: liang.
> [wang@aqara.com](mailto:wang@aqara.com)
> connect localhost:1883
> {"cmd":"write","id":2408,"did":"lumi.0","source":"","params":[{"res_name":"8.0.2
> 089","value":{"file_name":"./ControlBridge.bin","version":"V3.78"}}]}
> 
> on_connect result=0
> ota zigbee coordinator failed, errno =8
> `

Use absolute path

**Comment by miniknife88** [comment]
update zigbee firmware success，but firmware version in aqarahome has not changed.

**Comment by niceboygithub** [comment]
> update zigbee firmware success，but firmware version in aqarahome has not changed.

What the version  in gateway and in aqara home?

**Comment by miniknife88** [comment]
All use the latest version of firmware，after upgrading:
M2: 3.2.8_0006.0515
M1S: 3.2.8_0009.0519
