### ISSUE TITLE
P3更新失败，我是从修改版的4.0.1更新到4.0.6

### ISSUE THREAD

**Issue by iceskyh** [niceboygithub/AqaraM1SM2fw#93]
# chmod a+x /tmp/p3_update.sh && /tmp/p3_update.sh
p3_update.sh revision: 2
type: lumi.aircondition.acn05, model: AC_P3
platform: aiot, path: /tmp/fw.tar.gz, sign: 0
Unpack path : /tmp/ota_dir
Firmware path : /data/ota_dir
Available ROM size(b): 20213760
Available RAM size(b): 20381696
Update to 4.0.6_0006.0646
Get packages, please wait...
Got packages done
AalUart_Open /dev/ttyS2
recv STA!
recv close ACK!
recv CRC check!
ir ota successful ir_loacl_crc = 962b, ir_msg_crc=962b
Update failed, reason: OTA failed!

**Comment by niceboygithub** [comment]
It sometimes fails. Just retry
