### ISSUE TITLE
How to use TTL to flash modified firmware to M1S?

### ISSUE THREAD

**Issue by bbluvgg** [niceboygithub/AqaraM1SM2fw#96]
My M1S gateway firmware is 4.0.4_0006, cannot be opened Telnet and use with xiaomi gateway3.

I opened  the case of gateway , Connected  TTL to flash the modified firmware, but aqaragateway.exe displayed a failure：

If flash the latest linux_4.0.8_0006.0650_mi_4.0.4_0006.bin, it will display
![2](https://github.com/niceboygithub/AqaraM1SM2fw/assets/32580381/85cb8149-77be-4c4c-a4e2-01808fe55ba0)

If flash linux_3.2.7_0020.0524.bin, it will display
![1](https://github.com/niceboygithub/AqaraM1SM2fw/assets/32580381/037d4b9d-23d4-493a-aab3-153bcafe68be)

Is it my improper operation?I have connected to the GND/RX/TX points near the M1S MCU and provided it with 3.3V power supply.
![3](https://github.com/niceboygithub/AqaraM1SM2fw/assets/32580381/2107821a-8688-4297-b62f-5293c43d1ddf)
![4](https://github.com/niceboygithub/AqaraM1SM2fw/assets/32580381/1ec95d24-f70e-4e94-b225-e8dd30334104)

Is there any other way to flash the modified firmware, such as the traditional TTL mode?Is there a detailed tutorial?Thank you!

**Comment by niceboygithub** [comment]
You can just flash the 3.x rootfs_0 , donot use 4.x modified firmware to flash cause the size is too big.

**Comment by niceboygithub** [comment]
You can use the another method to clear password , please check the gw_global_tool
